apiVersion: v2
name: stackrox-operator
description: A Helm chart to distribute stackrox-operator
type: application

version: 4.11.0
appVersion: "4.11.0"

keywords:
  - kubernetes
  - operator

annotations:
  kubebuilder.io/generated-by: kubebuilder
