{{- include "srox.init" . -}}

{{- if ._rox.central._adminPassword -}}
{{- if ._rox.central._adminPassword.htpasswd -}}
apiVersion: v1
kind: Secret
metadata:
  name: central-htpasswd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "central-htpasswd") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "central-htpasswd") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  htpasswd: |
    {{- ._rox.central._adminPassword.htpasswd | nindent 4 }}

{{- end -}}
{{- end -}}
