{{- include "srox.init" . -}}

{{- if ._rox.imagePullSecrets._dockerAuths }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: stackrox
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "stackrox") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "stackrox") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
data:
  .dockerconfigjson: {{ dict "auths" ._rox.imagePullSecrets._dockerAuths | toJson | b64enc | quote }}
{{ end }}
