{{- include "srox.init" . -}}

{{- if ._rox._licenseKey -}}

apiVersion: v1
kind: Secret
metadata:
  name: central-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "central-license") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "central-license") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  license.lic: |
    {{- ._rox._licenseKey | nindent 4 }}

{{ end }}
