apiVersion: v2 
name: stackrox-secured-cluster-services
icon: https://raw.githubusercontent.com/stackrox/stackrox/master/image/templates/helm/shared/assets/Red_Hat-Hat_icon.png
description: Helm Chart for StackRox Secured Clusters
type: application
version: 400.3.2
appVersion: 4.3.2
