{{- include "srox.init" . -}}

{{- if ._rox.mainImagePullSecrets._dockerAuths }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: secured-cluster-services-main
  namespace: {{ ._rox._namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "secured-cluster-services-main") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "secured-cluster-services-main") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
data:
  .dockerconfigjson: {{ dict "auths" ._rox.mainImagePullSecrets._dockerAuths | toJson | b64enc | quote }}
{{ end }}
