{{- include "srox.init" . -}}

{{- if ._rox._additionalCAs }}
apiVersion: v1
kind: Secret
metadata:
  name: additional-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "srox.labels" (list . "secret" "additional-ca") | nindent 4 }}
  annotations:
    {{- include "srox.annotations" (list . "secret" "additional-ca") | nindent 4 }}
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  {{- range $name, $cert := ._rox._additionalCAs }}
  {{ $name | quote }}: |
    {{- $cert | nindent 4 }}
  {{- end }}
{{- end }}
